<?php
/**
 * @Date：2023/5/22 15:45
 * @Author LBG
 * @Link   http://www.hebei9.cn
 * @Copyright：Copyright (c) 2022 - 2035, 河北九米电子科技有限公司, Inc.
 */
declare(strict_types=1);
namespace Jiumi\Command;

use Hyperf\Command\Annotation\Command;
use Jiumi\JiumiCommand;

/**
 * Class JiumiAdmin
 * @package System\Command
 */
#[Command]
class JiumiAdmin extends JiumiCommand
{
    protected ?string $name = 'Jiumi';

    public function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    }

    /**
     * Handle the current command.
     */
    public function handle()
    {
        $result = shell_exec('php ' . BASE_PATH . '/bin/hyperf.php | grep Jiumi');
        $this->line($this->getInfo(), 'comment');
        $this->line(preg_replace('/\s+Jiumi\s+/', '', $result), 'info');
    }
}